import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  conteiner: {
    flex: 1,
    backgroundColor: '#0D1117',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  texto: {
    color: '#C9D1D9',
    fontSize: 24,
    fontFamily: 'inherit',
  },
  imagem: {
    padding: 20,
    margin: 25,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
  },
  nome: {
    color: '#C9D1D9',
    fontSize: 14,
    fontFamily: 'inherit',
    marginTop: 0,
    marginLeft: 15,
    margin: 10,
  },
  forget: {
    color: '#58A6FF',
    textAlign: 'right',
    fontSize: 12,
    fontFamily: 'inherit',
    paddingTop: 10,
  },
  login: {
    color: '#C9D1D9',
    width: 270,
    height: 35,
    borderColor: 'grey',
    borderWidth: 0,
    backgroundColor: 'transparent',
    borderWidth: 0.8,
    borderRadius: 6,
    marginLeft: 15,
    margin: 5,
    fontFamily: 'inherit',
  },
  box: {
    backgroundColor: '#161B22',
    color: 'white',
    width: 310,
    height: 290,
    marginBottom: 350,
    borderRadius: 6,
    fontFamily: 'inherit',
    paddingTop: 20,
    paddingRight: 20,
  },
  botao: {
    color: 'F0F6FC',
    backgroundColor: '#238636',
    width: 270,
    height: 35,
    borderWidth: 0,
    borderRadius: 6,
    marginTop: 25,
    marginLeft: 15,
    margin: 20,
  },
  tbutao: {
    fontFamily: 'inherit',
    textAlign: 'center',
    color: '#C9D1D9',
    fontWeight: 'bold',
    fontSize: 14,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
  },
  new: {
    borderColor: 'grey',
    borderWidth: 0.7,
    color: '#C9D1D9',
    alignItems: 'center',
    width: 310,
    height: 60,
    borderRadius: 6,
    fontFamily: 'inherit',
    paddingTop: 20,
    marginTop: 30,
  },
  texto1: {
    color: '#C9D1D9',
    fontSize: 14,
    fontFamily: 'inherit',
  },
  texto2: {
    color: '#58a6ff',
    fontSize: 12,
    fontFamily: 'inherit',
    marginBottom: 30,
    fontFamily: 'inherit',
    paddingTop: 20,
    alignItems: 'center',
    textAlign: 'center',
    paddingTop: 50,
  },
  create:{
    color: '#58a6ff'
  }
});