import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    conteiner: {
        flex: 1,
        backgroundColor: 'black',
        alignItems: 'center'
      },
      footer: {
        backgroundColor: '#161b21',
        width: 450,
        height: 80,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent:"space-between",
       alignItems:"stretch", 
        
      },
    imagem: {
        padding: 20,
        margin: 15,
        height: 10,
        width: 10,
        resizeMode: 'stretch',
        
    },
    box: {
      backgroundColor: '#161B22',
      color: 'white',
      width: 380,
      height: 330,
      fontFamily: 'inherit',
      borderRadius: 6,
      paddingTop: 30,
      paddingRight: 20,
    },
    repositories: {
      color: '#F0F6FC',
      textAlign: 'left',
      marginTop: 10, 
      marginRight: 300,
      marginBottom: 10
    },
    nome: {
      color: '#C9D1D9',
      fontSize: 14,
      fontFamily: 'inherit',
      marginTop: 0,
      marginLeft: 15,
      margin: 10,
    },
    more: {
      color: '#8B949E',
      fontSize: 10,
      fontFamily: 'inherit',
      marginTop: 23,
      marginLeft: 15,
      margin: 10,
    },
    repository: {
      color: '#C9D1D9',
      width: 360,
      height: 35,
      borderColor: 'grey',
      backgroundColor: '#010409',
      borderWidth: 0.7,
      borderRadius: 6,
      marginLeft: 10,
      marginBottom: 20,
      margin: 5,
      fontFamily: 'inherit',
    },
    repository1: {
      fontSize:10,
      width: 380,
      height: 35,
      borderColor: '#8B949E',
      borderWidth: 0,
      backgroundColor: '#161B22',
      borderWidth: 0.8,
      borderRadius: 6,
      marginLeft: 0,
      margin: 5,
      fontFamily: 'inherit',
    },
    imagemB: {
    padding: 10,
    margin: 0,
    height: 15,
    width: 15,
    alignItems: 'center',
    borderRadius: 60,
  },
  sectionStyle:{
      flexDirection: 'row',
      height: 30,
      borderRadius: 5,
      marginTop: 0,
      marginLeft:10,
    },
  sectionStyleC:{
      flexDirection: 'row',
      height: 30,
      borderRadius: 5,
      marginTop: 15,
      marginLeft:10,
    },
    imagemC: {
      padding: 15,
      margin: 0,
      height: 15,
      width: 15,
      borderRadius: 60,
    },
    nomeC: {
      color: '#F0F6FC',
      fontSize: 13,
      fontFamily: 'inherit',
      marginTop: 0,
      marginLeft: 15,
      margin: 10,
      fontWeight: 'bold'
    },
    box1: {
      backgroundColor: '#161B22',
      color: 'white',
      width: 310,
      height: 70,
      fontFamily: 'inherit',
      borderRadius: 6,
      paddingTop: 30,
      marginLeft: 30,
      borderColor: 'grey',
      borderWidth: 0.8
    },
    nomeD: {
      color: 'white',
      fontSize: 14,
      fontFamily: 'inherit',
      marginLeft: 10,
      marginTop: -20,
      fontWeight: 'bold'
    },
    nomeU: {
      color: '#8B949E',
      fontSize: 10,
      fontFamily: 'inherit',
      marginLeft: 10,
      marginTop: 10,
    },
      star: {
        marginTop: -30,
        marginLeft: 220,
        height: 20,
        width: 72,
      },
      nomeH: {
      color: '#8B949E',
      fontSize: 10,
      fontFamily: 'inherit',
      marginTop: -5,
      marginLeft: 55,
      margin: 5,
      },
      
      linha:{
        backgroundColor: '#8B949E',
        width: 360,
        height: 0.2,
        marginLeft: 10,
        
      },
      sectionStyleD:{
        flexDirection: 'row',
        height: 30,
        borderRadius: 5,
        marginTop: 10,
        marginLeft: -30,
      },
      nomeA: {
        color: '#8B949E',
        fontSize: 10,
        fontFamily: 'inherit',
        marginTop: -5,
        marginLeft: -220,
        margin: 5,
        },
        linhaB:{
          backgroundColor: '#8B949E',
          width: 380,
          height: 0.3,
          marginLeft: 10,
          marginTop: 10,
        },
        more1: {
          color: '#8B949E',
          fontSize: 10,
          fontFamily: 'inherit',
          marginTop: 10,
          marginStart: 20,

    },
    coluna: {
      backgroundColor: 'black',
      flexDirection: "row",
      justifyContent:"space-between",
      alignItems:"stretch", 
      
},
  ult:{
    marginRight: 130
  },
  botao: {
    backgroundColor: '#161B22',
    width: 380,
    height: 35,
    borderWidth: 0,
    borderRadius: 6,
    marginTop: 25,
    marginLeft: 15,
    margin: 20,
  },
  tbutao: {
    fontFamily: 'inherit',
    textAlign: 'center',
    color: '#58A6FF',
    fontWeight: 'bold',
    fontSize: 14,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
  },

});